# Generated by Django 3.2.4 on 2021-09-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_auto_20210904_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
